apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "conveyor.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.rootPassword | quote }}
