apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "conveyor.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.superuserPassword | quote }}
  {{- range $key, $db := .Values.postgres.databases }}
  {{ upper $key }}_DB_NAME: {{ $db.name | quote }}
  {{ upper $key }}_DB_USER: {{ $db.user | quote }}
  {{ upper $key }}_DB_PASSWORD: {{ $db.password | quote }}
  {{- end }}
  VERIFIER_DB_USER: {{ .Values.postgres.verifier.user | quote }}
  VERIFIER_DB_PASSWORD: {{ .Values.postgres.verifier.password | quote }}
